// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAukWSh5PQ0cVH732usEpHCDxF-Pj28TU4',
    appId: '1:932367678456:web:b3c0e85fbb024de260f40d',
    messagingSenderId: '932367678456',
    projectId: 'vault-ae5cb',
    authDomain: 'vault-ae5cb.firebaseapp.com',
    storageBucket: 'vault-ae5cb.firebasestorage.app',
    measurementId: 'G-DLD15PPT09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyhkn3-Is-06g6ug99Y_SdjNraXkw3F_A',
    appId: '1:932367678456:android:66d6d1d9496c0b4660f40d',
    messagingSenderId: '932367678456',
    projectId: 'vault-ae5cb',
    storageBucket: 'vault-ae5cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlQMHhN_WY-0a-3V_R9FPQnbqHoxpgq8',
    appId: '1:932367678456:ios:dda79f9c16f254ad60f40d',
    messagingSenderId: '932367678456',
    projectId: 'vault-ae5cb',
    storageBucket: 'vault-ae5cb.firebasestorage.app',
    iosClientId: '932367678456-nusbl6slaoc95klv1cjodif783oq23at.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBlQMHhN_WY-0a-3V_R9FPQnbqHoxpgq8',
    appId: '1:932367678456:ios:dda79f9c16f254ad60f40d',
    messagingSenderId: '932367678456',
    projectId: 'vault-ae5cb',
    storageBucket: 'vault-ae5cb.firebasestorage.app',
    iosClientId: '932367678456-nusbl6slaoc95klv1cjodif783oq23at.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAukWSh5PQ0cVH732usEpHCDxF-Pj28TU4',
    appId: '1:932367678456:web:0ac06e31e1e32a2b60f40d',
    messagingSenderId: '932367678456',
    projectId: 'vault-ae5cb',
    authDomain: 'vault-ae5cb.firebaseapp.com',
    storageBucket: 'vault-ae5cb.firebasestorage.app',
    measurementId: 'G-HDHG1ZEREE',
  );
}
